config/routes.rb
Rails.application.routes.draw do
  get 'genres/show'
  #顧客側のTOPページとaboutページのルーティング
  root "public/homes#top"
  get "about" => "public/homes#about"

  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

#管理者側のルーティング
  namespace :admin do
    root "homes#top"

    resources :customers,only: [:index, :show, :edit, :update] do
    end

    resources :items,only: [:new, :index, :show, :edit, :create, :update ] do
    end

    resources :genres,only: [:index, :edit, :create, :update ] do
    end

    resources :making_statuses,only: [:update] do
    end

    resources :orders,only: [:index, :show ] do
      patch '/orders/:id/order_status' => 'orders#order_status_update', as: "order_status" # 注文ステータスupdate
    end
  end

#顧客側のルーティング
  scope module: :public do
    resources :addresses,only: [:index, :edit, :create, :update, :destroy ] do
    end

    resources :cart_items,only: [:index, :create, :update, :destroy ] do
      collection do
        delete 'all_destroy'
      end
    end

    patch '/customers/withdraw' => 'customers#withdraw', as: 'withdraw'
    get 'customers/unsubscribe' => 'customers#unsubscribe', as: 'unsubscribe'
    resources :customers,only: [:show, :edit, :update ] do
    end

    resources :items,only: [:index, :show ] do
    end

    get 'orders/finish' => 'orders#finish'
    post 'orders/comfirm' => 'orders#comfirm'
    resources :orders,only: [:new, :create, :index, :show ] do
    end

    resources :genres, only: [:show]
  end

end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  validates :postal_code,presence:true
  validates :address,presence:true
  validates :name,presence:true

  def address_display
    '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to:customer
  belongs_to:item


#税込み価格＊個数
  def subtotal
    item.with_tax_price*quantity
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items
  has_many :addresses

  validates :last_name, :kana_last_name, :postal_code, :address, :tel_number, presence:true


  def active_for_authentication?
    super && (is_deleted == false)
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items,dependent: :destroy
  validates :name, {presence: true}
end

app/models/item.rb
class Item < ApplicationRecord

  has_one_attached:image

  has_many :cart_items,dependent: :destroy
  has_many :ordered_items,dependent: :destroy

  
  has_many :ordered_items  #中間テーブル
  has_many :orders, through: :ordered_items
  

  belongs_to :genre

  #税込み価格
 def with_tax_price
    (price * 1.1).floor
 end

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :ordered_items
  has_many :items, through: :ordered_items

  validates :name, :postal_code, :address, presence:true

  enum payment_type: { credit_card: 0, transfer: 1 }

  # 注文ステータス（0=入金待ち / 1=入金確認 / 2=制作中 / 3=発送準備中 / 4=発送済み）
  enum status: {
      waiting: 0,
      paid_up: 1,
      making: 2,
      preparing: 3,
      shipped: 4
  }

  def address_name
    postal_code + address + name
  end

  after_update do
    if self.status == "paid_up" #入金確認の更新があった時
        self.ordered_items.each do|ordered_item|
        ordered_item.update(making_status: "make_waiting" ) #製作ステータスを製作待ちに変更する
      end
    end
  end
end

app/models/ordered_item.rb
class OrderedItem < ApplicationRecord
  belongs_to :order
  belongs_to :item

  enum making_status: {
    no_making: 0,
    make_waiting: 1,
    making: 2,
    making_complete: 3
  }

  #税込み価格＊個数
  def subtotal
    item.with_tax_price*quantity
  end

  after_update do
    if self.order.ordered_items.exists?(making_status: 2 )
      self.order.update(status: 2 ) # 注文ステータスを製作中に変更する
    elsif self.order.ordered_items.where(making_status: 3 ).count == self.order.ordered_items.count
      self.order.update(status: 3 ) # 注文ステータスを発送準備中に変更する
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!

  def show
    @order = Order.find(params[:id])
    @ordered_items = @order.ordered_items.all
    @items_total_price = calculate(@order)
  end

  def calculate(items_total_price) # 商品合計を算出するメソッド
    @items_total_price = 0
    @ordered_items.each {|ordered_item|
    tax_in_price = (ordered_item.taxed_price).floor
    sub_total_price = tax_in_price * ordered_item.quantity
    @items_total_price += sub_total_price
    }
    return @items_total_price
  end

  def order_status_update
    order = Order.find(params[:id])
    if order.update(order_params)
      redirect_to admin_order_path(order)
      flash[:success] = "注文ステータスを更新しました"
    else
      render :show
      flash[:success] = "注文ステータスを更新できませんでした"
    end
  end

  private

  def order_params
    params.require(:order).permit(:status)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   before_action :configure_permitted_parameters, if: :devise_controller?

   before_action :set_search

  private
    def set_search
      @q = Item.ransack(params[:q])
      @items = @q.result(distinct: true)
    end

  protected

   def after_sign_in_path_for(resource)
      if customer_signed_in?
        root_path
      else
        admin_root_path
      end
   end

  def after_sign_out_path_for(resource)
    if customer_signed_in?
    root_path
    else
    customer_session_path
    end
  end
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :kana_first_name, :kana_last_name, :email, :address, :postal_code, :tel_number])

  	devise_parameter_sanitizer.permit(:sign_in, keys: [:email])
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
  end

  def show
  end
  
  def create
  end
  
  def update
  end
  
  def destory
  end
  
  def all_destroy
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def new
  end

  def log
  end

  def finish
  end

  def index
  end

  def show
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/admin/orders/show.html.erb
<div class="container my-5">
  <div class="row">
    <h2>注文詳細</h2>
  </div>
  <div class="row mt-3">
    <div class="col-sm-9">
      <table class="table table-striped table-bordered bg-light">
        <tbody>
          <tr>
            <td>
              <i class="fas fa-user fa-lg"></i>購入者
            </td>
            <td>
              <%= @order.customer.last_name %>
              <%= @order.customer.first_name %>
            </td>
          </tr>
          <td>
            <i class="fas fa-calendar-alt fa-lg"></i>注文日
          </td>
          <td><%= @order.created_at.strftime('%Y/%m/%d(%a)') %></td>
          <tr>
            <td>
              <i class="fas fa-truck fa-lg"></i>配送先
            </td>
            <td>
              〒<%= @order.postal_code %>
              <%= @order.address %>
              <%= @order.customer.last_name %>
              <%= @order.customer.first_name %>
            </td>
          </tr>
          <tr>
            <td>
              <i class="fas fa-search-dollar fa-lg"></i>支払方法
            </td>
            <td><%= @order.payment_type_i18n %></td>
          </tr>
          <tr>
            <td>
              <i class="fas fa-check-square fa-lg"></i>注文ステータス
            </td>
            <td>
              <%= form_with model: @order, url: admin_order_order_status_path(@order), method: :patch do |f| %>
                <%= f.select :status, Order.statuses_i18n.invert,{prompt: false}, class: "form-control-inline form-control-sm col-6" %>
                <%= f.submit "更新", class: "btn btn-primary btn-sm" %>
              <% end %>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
  <div class="row mt-3 ">
    <div class="col-lg-9">
      <table class="table table-striped table-bordered bg-light">
        <thead>
          <tr>
            <th>商品名</th>
            <th>単価(税込)</th>
            <th>数量</th>
            <th>小計</th>
            <th>製作ステータス</th>
            <th colspan="1"></th>
          </tr>
        </thead>
        <% @ordered_items.each do |ordered_item| %>
        <tbody>
          <tr>
            <td><%= ordered_item.item.name %></td>
            <td><%= (ordered_item.item.price * 1.1).floor.to_s(:delimited) %>円</td>
            <td><%= ordered_item.quantity %>個</td>
            <td><%= (ordered_item.item.price * ordered_item.quantity * 1.1).floor.to_s(:delimited) %>円</td>
            <td>
              <%= form_with model: ordered_item, url: admin_making_status_path(ordered_item, order_id: @order.id), method: :patch do |f| %>
                <%= f.select :making_status, OrderedItem.making_statuses_i18n.invert,{prompt: false}, class: "form-control-inline form-control-sm col-6"  %>
                <%= f.submit "更新", class: "btn btn-primary btn-sm" %>
              <% end %>
            </td>
          </tr>
        </tbody>
        <% end %>
      </table>
    </div>
  </div>
  <div class="col-lg-4">
    <table class="table table-borderless align-self-end">
      <tbody>
        <tr class="border-bottom border-dark">
          <td>商品合計</td>
          <td><%= @items_total_price.floor.to_s(:delimited) %>円</td>
        </tr>
        <tr class="border-bottom border-dark">
          <td>送料</td>
          <td><%= @order.postage %>円</td>
        </tr>
        <tr class="border-bottom border-dark">
          <td>請求金額合計</td>
          <td><%= (@items_total_price + @order.postage).floor.to_s(:delimited) %>円</td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

app/views/orders/finish.html.erb
<h1>Orders#finish</h1>
<p>Find me in app/views/orders/finish.html.erb</p>

app/views/orders/index.html.erb
<h1>Orders#index</h1>
<p>Find me in app/views/orders/index.html.erb</p>

app/views/orders/log.html.erb
<h1>Orders#log</h1>
<p>Find me in app/views/orders/log.html.erb</p>

app/views/orders/new.html.erb
<h1>Orders#new</h1>
<p>Find me in app/views/orders/new.html.erb</p>

app/views/orders/show.html.erb
<h1>Orders#show</h1>
<p>Find me in app/views/orders/show.html.erb</p>