config/routes.rb
Rails.application.routes.draw do
  get 'genres/show'
  #顧客側のTOPページとaboutページのルーティング
  root "public/homes#top"
  get "about" => "public/homes#about"

  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

#管理者側のルーティング
  namespace :admin do
    root "homes#top"

    resources :customers,only: [:index, :show, :edit, :update] do
    end

    resources :items,only: [:new, :index, :show, :edit, :create, :update ] do
    end

    resources :genres,only: [:index, :edit, :create, :update ] do
    end

    resources :making_statuses,only: [:update] do
    end

    resources :orders,only: [:index, :show ] do
      patch '/orders/:id/order_status' => 'orders#order_status_update', as: "order_status" # 注文ステータスupdate
    end
  end

#顧客側のルーティング
  scope module: :public do
    resources :addresses,only: [:index, :edit, :create, :update, :destroy ] do
    end

    resources :cart_items,only: [:index, :create, :update, :destroy ] do
      collection do
        delete 'all_destroy'
      end
    end

    patch '/customers/withdraw' => 'customers#withdraw', as: 'withdraw'
    get 'customers/unsubscribe' => 'customers#unsubscribe', as: 'unsubscribe'
    resources :customers,only: [:show, :edit, :update ] do
    end

    resources :items,only: [:index, :show ] do
    end

    get 'orders/finish' => 'orders#finish'
    post 'orders/comfirm' => 'orders#comfirm'
    resources :orders,only: [:new, :create, :index, :show ] do
    end

    resources :genres, only: [:show]
  end

end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  validates :postal_code,presence:true
  validates :address,presence:true
  validates :name,presence:true

  def address_display
    '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to:customer
  belongs_to:item


#税込み価格＊個数
  def subtotal
    item.with_tax_price*quantity
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items
  has_many :addresses

  validates :last_name, :kana_last_name, :postal_code, :address, :tel_number, presence:true


  def active_for_authentication?
    super && (is_deleted == false)
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items,dependent: :destroy
  validates :name, {presence: true}
end

app/models/item.rb
class Item < ApplicationRecord

  has_one_attached:image

  has_many :cart_items,dependent: :destroy
  has_many :ordered_items,dependent: :destroy

  
  has_many :ordered_items  #中間テーブル
  has_many :orders, through: :ordered_items
  

  belongs_to :genre

  #税込み価格
 def with_tax_price
    (price * 1.1).floor
 end

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :ordered_items
  has_many :items, through: :ordered_items

  validates :name, :postal_code, :address, presence:true

  enum payment_type: { credit_card: 0, transfer: 1 }

  # 注文ステータス（0=入金待ち / 1=入金確認 / 2=制作中 / 3=発送準備中 / 4=発送済み）
  enum status: {
      waiting: 0,
      paid_up: 1,
      making: 2,
      preparing: 3,
      shipped: 4
  }

  def address_name
    postal_code + address + name
  end

  after_update do
    if self.status == "paid_up" #入金確認の更新があった時
        self.ordered_items.each do|ordered_item|
        ordered_item.update(making_status: "make_waiting" ) #製作ステータスを製作待ちに変更する
      end
    end
  end
end

app/models/ordered_item.rb
class OrderedItem < ApplicationRecord
  belongs_to :order
  belongs_to :item

  enum making_status: {
    no_making: 0,
    make_waiting: 1,
    making: 2,
    making_complete: 3
  }

  #税込み価格＊個数
  def subtotal
    item.with_tax_price*quantity
  end

  after_update do
    if self.order.ordered_items.exists?(making_status: 2 )
      self.order.update(status: 2 ) # 注文ステータスを製作中に変更する
    elsif self.order.ordered_items.where(making_status: 3 ).count == self.order.ordered_items.count
      self.order.update(status: 3 ) # 注文ステータスを発送準備中に変更する
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
  end

  def show
  end
  
  def create
  end
  
  def update
  end
  
  def destory
  end
  
  def all_destroy
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def new
  end

  def log
  end

  def finish
  end

  def index
  end

  def show
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class='container-fluid mt-5 p-3 mb-2 bg-secondary text-white'>
  	<div class='row'>
    	<div class='mx-auto'>

    		<div class="text-center">
    		  <i class="fab fa-instagram"></i>
      		<i class="fab fa-facebook-square"></i>
      		<i class="fab fa-twitter"></i>
    		</div>
    		<div class="mt-3">
    		<i class="fas fa-phone"></i>xxx-xxxx-xxxx</p>
      	<i class="fas fa-map-marker-alt"></i></i>長野県〇〇市〇〇町１－１－１</p>
      	<i class="fas fa-paper-plane"></i>xxx@xxx.xxx</p>
      	<p class="copyright">
          COPYRIGHT © Mens DWC
        </p>
    	</div>
    	</div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="shadow-sm">

  <nav class="navbar navbar-expand-lg navbar-white" style="background-color: #5DADE2;">
    <div class="container">
      <a class="navbar-brand p-3" href="/"><%= image_tag('logo2.jpg', size: "100x100") %></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
        <% if customer_signed_in? %>
        <li class="nav-item">
            ようこそ、<%= current_customer.last_name %>さん！
        </li>

        <li class="nav-item">
          <%= link_to customer_path(current_customer), class: 'nav-link text-dark' do %>
          <i class="fas fa-user-alt"></i> マイページ
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to items_path, class: 'nav-link text-dark' do %>
          <i class="fas fa-birthday-cake"></i> 商品一覧
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to cart_items_path, class: 'nav-link text-dark' do %>
          <i class="fas fa-shopping-cart"></i> カート
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to destroy_customer_session_path, method: :delete, class: 'nav-link text-dark' do %>
          <i class="fas fa-sign-out-alt"></i> ログアウト
          <% end %>
        </li>
        <%= render 'layouts/search' %>

        <% elsif admin_signed_in? %>
        <li class="nav-item">
          <%= link_to admin_items_path, class: 'nav-link text-dark' do %>
          <i class="fas fa-birthday-cake"></i> 商品一覧
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to admin_customers_path, class: 'nav-link text-dark' do %>
          <i class="fas fa-users"></i> 会員一覧
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to admin_root_path, class: 'nav-link text-dark' do %>
          <i class="fas fa-history"></i> 注文履歴一覧
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to admin_genres_path, class: 'nav-link text-dark' do %>
          <i class="fas fa-candy-cane"></i> ジャンル一覧
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to destroy_admin_session_path, method: :delete, class: 'nav-link text-dark' do %>
          <i class="fas fa-sign-out-alt"></i> ログアウト
          <% end %>
        </li>
        <%= render 'layouts/search' %>
        <% else %>
        <li class="nav-item">
          <%= link_to about_path, class: 'nav-link text-dark' do %>
          <i class="fas fa-store"></i> About
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to items_path, class: 'nav-link text-dark' do %>
          <i class="fas fa-birthday-cake"></i> 商品一覧
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to new_customer_registration_path, class: 'nav-link text-dark' do %>
          <i class="fas fa-user-plus"></i> 新規登録
          <% end %>
        </li>
         <li class="nav-item">
          <%= link_to new_customer_session_path, class: 'nav-link text-dark' do %>
          <i class="fas fa-sign-in-alt"></i> ログイン
          <% end %>
        </li>
        <%= render 'layouts/search' %>
        <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/_search.html.erb
<%= search_form_for @q, url: items_path, class:"search-form" do |f| %>
  <%= f.search_field :name_cont, placeholder: '商品名から探す' %>
  <%= button_tag :type => "submit", :class =>"btn btn-default btn-s-md" do %>
  <i class="fa fa-search"></i>検索
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body style="background-color:#FFFFFF ;">

    <%= render 'layouts/header' %>
      <% if notice %>
      	<div class="alert alert-success text-center">
      	  <span id="notice"><%= notice %></span>
      	</div>
      <% elsif flash[:success] %>
      	<div class="alert alert-success text-center">
        	<span id="success"><%= flash[:success] %></span>
      	</div>
      <% elsif flash[:alert] %>
      	<div class="alert alert-danger text-center">
      	  <span id="alert"><%= flash[:alert] %></span>
      	</div>
      <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>